### ISSUE TITLE
Error al calcular número de trastes visibles

### ISSUE THREAD

**Issue by acpride** [choan/fretboards#1]
Hola, 

En algunos diagramas no se calcula bien el número de trastes visibles necesarios para renderizar correctamente el diagrama. Por ejemplo:

```
require "fretboards"
require "fretboards/fretboard_collection"
  
chords = Fretboards::FretboardCollection.new
chords.set_tuning(%w{ g' c' e' a' })

chords.define("D (1)", %w{ 7-3/4(1)! 6-2/3(3) 5-1/2(5) 9-4/1(3) })
```

(adjunto el svg resultante)

En cambio en otros acordes donde incluso hay más trastes de separación, se muestra correctamente, por ejemplo:

`chords.define("C (1)", %w{ 0(5) 0(1)! 3-1/2(5) 7-4/1(3) })`

Gracias

![d 1](https://user-images.githubusercontent.com/7589079/28566289-f71daf62-712e-11e7-88c0-fb8c951d4f20.png)
![c 1](https://user-images.githubusercontent.com/7589079/28566290-f721cf66-712e-11e7-93a2-5049b034126d.png)

**Comment by choan** [comment]
@acpride Solved in 0.0.4
